import type { Metadata } from "next";
import "./globals.css";
import { Inter, Caveat } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Define a CSS variable for global usage
});

const caveat = Caveat({
  subsets: ["latin"],
  weight: ["400", "700"], // Include weights as needed
  variable: "--font-caveat", // Define a CSS variable for selective usage
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${inter.variable} ${caveat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
